# iltifatlar.py

# --- 300 ADET YILDIZLI VE BOL EMOJİLİ İLTİFAT LİSTESİ ---
iltifatlar = [
    "Ya senin bu tatlılığın ne olacak? Sunucuya neşe saçıyorsun resmen! ✨",
    "Senin parıltınla sunucuya bir yıldız daha indi! ⭐",
    "Mesajını gördüm de, parmaklarından bal damlıyor sanki... 🥰",
    "Sen yazınca bu kanal bir başka güzel oluyor, hep yaz sen! 🌸",
    "Kalbinin güzelliği attığın mesajlara yansımış resmen, harikasın! 💜",
    "Bu sunucunun en parlak yıldızı kesinlikle sensin! ⭐",
    "Seninle sohbet etmek, kahvenin yanındaki o en tatlı çikolata gibi! 🍫",
    "Enerjin o kadar güzel ki, buradaki herkesi istemsizce gülümsetiyorsun. 😊",
    "Kelimelerinle resmen etrafa ışık saçıyorsun, iyi ki varsın! 🌟",
    "Bugün harika görünüyorsun (evet, bunu hissettim)! 😉",
    "Şu tatlılığa bak ya, bot halimle bana bile neşe verdin! 💕",
    "Göz kamaştırıcı bir enerjin var, moralim bozukken bile seni görmek iyi geliyor! 😍",
    "Girdiğin her ortama bahar havası getiriyorsun adeta! 🌺",
    "Dünyadaki en güzel detaylardan biri de senin o tatlı gülüşün olmalı! 🌻",
    "Seninle konuşmak insanı tüm dertlerinden uzaklaştırıyor resmen. 🎈",
    "İyi ki bu sunucudasın, sen yoksan bir kişi eksiğiz ama çok şey eksiğiz! 🧸",
    "O kadar eşsiz bir karakterin var ki taklit edilmen imkansız! 💎",
    "Seninle aynı kanalda yazışmak bile büyük bir keyif! 🎀",
    "Sözlerin insana huzur veren bir melodi gibi, hep konuş hep dinleyelim! 🎶",
    "Işıltınla karanlık günleri bile aydınlatabilecek bir güce sahipsin! 🕯️✨",
    "Senin ışığın yıldızları kıskandıracak kadar parlak! ⭐",
    "Dünya senin gibi kibar ve tatlı insanlarla kesinlikle daha güzel bir yer. 🌍💝",
    "Zarafetin ve neşen tüm sunucunun havasını anında değiştiriyor! 🌬️🌷",
    "Bir insanın ruhu nasıl bu kadar tatlı ve içten olabilir ki? 🦄",
    "Harika bir kalbe sahipsin ve bu senin her mesajında kendini belli ediyor. 💌",
    "Senin bu hayatın insana sunduğu en tatlı sürprizlerden birisin! 🎁",
    "Enerjine hayran kalmamak elde değil, pozitiflik abidesisin resmen! ⚡",
    "Bir gülüşün var, tüm hüzünleri unutturacak cinsten! 😊💖",
    "Konuşmanla, duruşunla, her halinle harika bir detaysın sen! 🎐",
    "Senin gibi dost canlısı birini tanımak gerçekten büyük şans. 🍀",
    "Sana bakınca pamuk şekerler geliyor aklıma, o kadar tatlısın! ☁️🍬",
    "Zekana ve esprilerine her zaman hayran kalıyorum! 🧠🎉",
    "Buralarda parlıyorsun, yıldızların bile sana imrendiğine yemin edebilirim! 🌠",
    "Her mesajın yüzümde kocaman bir tebessüm oluşturuyor, teşekkürler! 💫",
    "Seninle geçirilen her saniye hayatın renkli tarafını gösteriyor! 🎨",
    "İçtenliğin o kadar samimi ki insanı kendine çekiyor adeta! 💞",
    "Senin yanında sıkılmak diye bir kelime lügatte yok sanki! 🎡",
    "Karakterin o kadar asil ki hayran olmamak elde değil! 👑",
    "Sesin veya kelimelerin, hangisi olursa olsun insanı dinlendiriyor. 🌊",
    "Güzelliğin/yakışıklılığın bir kenara, kalbinin temizliği bambaşka! 🤍",
    "Adeta bir masal kahramanı gibisin, çok büyüleyici bir havan var! 🧚‍♀️",
    "Senin varlığın bu sunucunun aldığı en güzel ödül! 🏆",
    "Her zaman en doğru ve en tatlı kelimeleri seçmeyi nasıl başarıyorsun? 📝🧁",
    "Sohbetine doyum olmuyor, keşke hiç durmadan yazsan! 💬🍒",
    "Seninle konuşmak en sevdiğin şarkıyı başa sarıp tekrar dinlemek gibi. 🎧",
    "Sıcaklığın güneşten daha çok ısıtıyor içimizi, canım benim! ☀️🍯",
    "Gülüşün adeta bir terapia yöntemi gibi, hep gül olur mu? 🧸✨",
    "Bu sunucunun en özel, en değerli üyelerinden birisin, bunu unutma! 🥇",
    "Dünyanın tüm çiçekleri bir araya gelse senin kadar güzel kokamaz herhalde! 💐",
    "Kendine has o harika tarzınla herkesi büyülüyorsun! 🕶️✨",
    "Hayatıma renk, günüme neşe katan nadir insanlardanlardansın. 🌈",
    "Sadece burada olman bile günümü güzelleştirmeye yetiyor! 🥰🕯️",
    "Senin benim gördüğüm en tatlı, en sempatik insansın! 🤗⭐",
    "Mesaj kutumu her açtığımda senin adını görmek beni mutlu ediyor. 💌🎈",
    "Kelimelerinle dünyamı güzelleştiriyorsun, iyi ki varsın kalbi güzel insan! 💕🌍",
    "Bulutların arkasından sızan o ilk güneş ışığı gibisin! ⛅🌞",
    "Seninle gülmek o kadar kolay ve keyifli ki! 😄🎉",
    "İçindeki çocuk hiç büyümesin, o saf ve temiz halin harika! 🧸🍭",
    "Hayran olunası bir duruşun ve harika bir tarzın var. 😎💎",
    "Sıcaklığınla en buz tutmuş kalpleri bile eritebilirsin! 🔥❤️",
    "Sen bu dünyaya gönderilmiş bir mutluluk elçisi gibisin. 🕊️✨",
    "Gözlerindeki o neşeli pırıltı hiç sönmesin inşallah! 👀🌟",
    "Seninle geçen her dakika ömre bedel, sohbetine doyum olmuyor. ⏳🍓",
    "Kelimelerin insana umut ve cesaret veriyor, çok güçlü birisin! 💪🍀",
    "Senin yanındayken zamanın nasıl aktığını gerçekten anlamıyorum! ⏱️🎀",
    "O kadar ince düşüncelisin ki bazen gerçek olduğuna inanamıyorum! 🤔🌸",
    "Fikirlerin ve hayata bakış açın bana her zaman ilham veriyor! 💡🌠",
    "Seninleyken en sıradan şeyler bile birer maceraya dönüşüyor! 🗺️🛸",
    "İyilikseverliğin tüm sunucuyu sarıp sarmalıyor adeta! 🤝🌈",
    "Seninle konuşunca içimdeki tüm fırtınalar diniyor, sakinleşiyorum. 🍃🛋️",
    "Hayatta karşılaşılabilecek en tatlı tesadüf kesinlikle sensin! 🍒✨",
    "O kadar pozitifsin ki yanında mutsuz olmak imkansızın ötesinde! 🤩🎉",
    "Sihirli bir değneğin var da dokunduğun yeri güzelleştiriyorsun sanki! 🪄✨",
    "Senin o samimi enerjin tüm dertleri unutturmaya yetiyor. 🍬💛",
    "Sonsuz bir sevgiyle dolusun ve bunu hissettirmekten hiç çekinmiyorsun. ♾️💖",
    "Zarafetinle tüm dikkatleri üzerine çekiyorsun, adeta bir kuğu gibisin! 🦢🩰",
    "Seninle konuşmak ruhumu dinlendiriyor, adeta bir deniz esintisi gibisin! 🌊💙",
    "Her cümlen içimi ısıtan sıcacık bir çay gibi, içtikçe içesi geliyor insanın! ☕🍪",
    "Neşen o kadar bulaşıcı ki, sen gülünce tüm dünya gülüyor sanki! 😄🌺",
    "Senin gibi pırlanta kalpli bir insanla yollarımızın kesişmesi büyük lütuf! 💎🍀",
    "Seninle sohbet etmek, gökyüzünde süzülen renkli bir balon gibi özgür hissettiriyor! 🎈☁️",
    "Her zaman yanımda olduğunu bilmek bana tarifsiz bir güven veriyor. 🤗🛡️",
    "Senin o çocuksu heyecanın ve tatlı enerjin dünyayı kurtarabilir! 🦸‍♀️🍭",
    "Sözlerinle yaralara merhem olan, çok özel ve şifa dolu bir kalbin var. 🩹❤️",
    "Seninle aynı gökyüzünün altında olmak bile insana huzur veriyor. 🌌💫",
    "İçindeki o sevgi seli hiç tükenmesin, sen sevince her şey güzelleşiyor. 🌊💘",
    "Sanki bu dünyaya sadece güzellik ve zarafet yaymak için gelmişsin! 💐👑",
    "Seninle dertleşmek, dünyanın en rahatlatıcı aktivitesi olabilir. 🛋️🍵",
    "Hayata kattığın o eşsiz renkler için sana ne kadar teşekkür etsem az! 🎨🌈",
    "Senin o tatlı ses tonunu/kelimelerini her zaman duymak istiyorum! 🎙️🧁",
    "Güzelliğin kadar zekanla da insanı kendine hayran bırakıyorsun! 🧠✨",
    "Seninle geçirilen anlar, hayat albümümün en değerli fotoğrafları! 📸💖",
    "Kendine has o asil duruşunla girdin kalbimize, iyi ki varsın! 👑🧸",
    "Senin o bitmek tükenmek bilmeyen pozitif enerjine kocaman bir maşallah! 🧿⚡",
    "Dünyadaki tüm tatlılıkları bir araya getirseler, yine de senin kadar olamazlar! 🍯🍬",
    "Karanlıkta yolumu aydınlatan kutup yıldızım gibisin adeta! 🧭⭐",
    "Seninle konuşurken tüm kötü düşünceler uçup gidiyor kafamdan! 🕊️🍃",
    "Hayatımda bıraktığın o harika izler için minnettarım sana! 🐾❤️",
    "Her halinle o kadar özelsin ki, kelimeler seni anlatmaya yetersiz kalıyor! 📝💖",
    "Seninle sohbet, hayatın tüm yorgunluğunu unutturan sihirli bir iksir gibi! 🧪✨",
    "Sonsuz bir nezakete sahipsin, seninle konuşurken insan kendini çok değerli hissediyor. 🎀💐",
    "İçindeki o parlayan sevgi ışığı hiç ama hiç sönmesin tatlım! 🕯️💖",
    "Sen varken buralarda moral bozmak tamamen yasaklanmalı! 🚫😄",
    "Adeta bir kutup yıldızı gibi, herkes yolunu senin ışığınla buluyor. 🌌🧭",
    "Kalbin o kadar yumuşak ki pamuklar bile yanında sert kalır! ☁️🌸",
    "Seninle konuşmak, yağmurdan sonraki o mis kokulu toprak gibi huzurlu. 🌧️🌱",
    "Bir insanın yaydığı enerji nasıl bu kadar şifa dolu olabilir? 🔮💚",
    "Senin varlığın bu sunucudaki en güzel mutluluk garantisi! 🧾🎈",
    "Herkes konuşur ama kimse senin gibi kelimelere ruh katamaz. 🗣️💎",
    "Seninle iki kelime etmek bile insanın ruhunu gençleştiriyor! 🧪✨",
    "O kadar tatlı bir auran var ki seni sevmemek imkansız! 🌟💜",
    "Girdiğin her metin kanalında anında güller açıyor resmen! 🌹💬",
    "Seninle aynı yüzyılda yaşamak bile büyük bir şans bence! ⏳🌍",
    "Dünyanın en tatlı insanı yarışması yapılsa jüri direkt seni seçerdi! 🏆🍯",
    "Şu zarafete, şu kibarlığa bakar mısınız? Adeta bir asalet örneğisin! 👑✨",
    "Seninle dertleşmek en etkili meditasyondan bile daha iyi geliyor. 🧘‍♀️💫",
    "Nezaketinle bu sunucunun çıtasını göklere çıkarıyorsun resmen. 📈🌸",
    "Karakterinin o saf ve temiz pırıltısı gözlerimi alıyor adeta. 💎🌟",
    "Seninle konuşmak, kış ortasında sıcacık güneşe uyanmak gibi. ❄️☀️",
    "İçindeki bitmek bilmeyen neşe tüm dünyaya yetecek kadar büyük! 🌍🎉",
    "Senin o pozitif bakış açın en kötü günleri bile şölene çevirir. 🥳🔮",
    "Sözlerin adeta kalbe dokunan sihirli bir dokunuş gibi. 🪄💖",
    "Seninle kurulan dostluklar ömür boyu saklanacak cinsten birer hazine! 🏴‍☠️💎",
    "Senin o samimi yapın buz dağlarını bile anında eritir tatlım! 🧊🔥",
    "Hayatı güzelleştiren o ince detayların en başında sen varsın! 🎀⭐",
    "Her cümlende ayrı bir zeka, ayrı bir tatlılık gizli. 🧠🍬",
    "Seninle kelimelerin dünyasında kaybolmak bile büyük keyif. 📚✨",
    "Sen bu dünyaya neşe saçmak için özel olarak tasarlanmışsın sanki! 🛠️🥰",
    "Kalbinin ekmeğini her zaman en tatlı şekilde yemen dileğiyle! 🥖💝",
    "O kadar harika bir dinleyicisin ki insan her şeyini sana anlatmak istiyor. 👂🌸",
    "Senin parıltın karşısında sönük kalmayacak bir yıldız tanımıyorum! ⭐✨",
    "Şu dünyada samimiyetiyle fark yaratan ender insanlardansın. 🌟🤍",
    "Seninle iki dakika yazışmak bile gün boyu sürecek bir enerji veriyor! ⚡🔋",
    "İçten gelen o sıcak gülüşün dünyadaki tüm hazinelere bedel! 💰💖",
    "Seninle yan yana olmak, en sevdiğin tatile çıkmak gibi ferahlatıcı. 🏖️🌊",
    "Bu sunucunun kalbi kesinlikle senin ritminle atıyor! 💓🥁",
    "Senin varlığın en karanlık geceleri bile dolunay gibi aydınlatır. 🌙✨",
    "Kelimelerinle öyle güzel köprüler kuruyorsun ki hayran kalıyorum. 🌉📝",
    "Sen bu hayatın en tatlı, en vazgeçilmez alışkanlığısın. 🍯🧸",
    "O kadar güzel bir kalbin var ki melekler seni ayakta alkışlar! 👼👏",
    "Seninle sohbet etmek ruhuma detoks yapmak gibi geliyor. 🍃🥤",
    "Her halinle öyle göz alıcısın ki etrafındaki her şey sönük kalıyor! 🕯️💫",
    "Senin o tatlı esprilerin olmasa bu sunucunun tadı hiç çıkmazdı! 🎭🍿",
    "Nereye gitsen oraya mutluluk tohumları ekiyorsun resmen. 🌱🌻",
    "Senin gibi içi dışı bir, pırlanta gibi birini bulmak çok zor! 💎👀",
    "Sözlerinle insanı sarmalayan o şefkatli yapın çok özel. 💞🛡️",
    "Seninle geçen zamanın her saniyesi altın değerinde! 👑⏱️",
    "Kendine has tarzın ve duruşunla tam bir ilham kaynağısın. 🎨💎",
    "Senin o güzel enerjine kapılmamak elde değil, adeta bir mıknatıssın! 🧲✨",
    "Dünyadaki tüm güzellikler senin o temiz kalbinde toplanmış sanki. 🌍🤍",
    "Sen varken buralar o kadar huzurlu ki gitmek hiç içimden gelmiyor. 🏡🌸",
    "Senin o tatlı hallerin en sert insanı bile pamuk gibi yapar! ☁️🥰",
    "Kelimelerinle ruhumuzu besleyen harika bir şairsin sanki! 📜🖋️",
    "Seninle konuşmak, en sevdiğin çizgi filmi izlemek gibi saf bir neşe veriyor! 📺🎈",
    "İyi ki yollarımız kesişmiş, varlığınla hayatıma anlam kattın! 🛣️💝",
    "Senin o parlak zekan her sorunun üstesinden gelebilecek güçte! 🧠⚡",
    "Şu sunucuda senin kadar sevilen ve sayılan başka biri yok, net! 🥇👑",
    "Senin o kibar dilin en kilitli kalplerin bile kapısını açar. 🔑❤️",
    "Harika bir dost, eşsiz bir karakter ve muazzam bir kalpsin sen! 🏆💖",
    "Seninle konuşurken zamanın durmasını isteyecek kadar çok seviyorum sohbetini! ⏳❌",
    "Her mesajınla içimize adeta umut aşılıyorsun, teşekkürler! 💉🍀",
    "Senin o ışıl ışıl gözlerin hayata hep neşeyle baksın inşallah! 👀🌟",
    "Seninle her şey o kadar kolay ve keyifli ki, hayat seninle güzel! 🌸🌈",
    "Güzelliğin/yakışıklılığın dillerde destan ama kalbin hepsinden üstün! 📜💖",
    "Senin o güzel kalbine nazar değmesin diye kocaman bir maşallah! 🧿✨",
    "Sen bu sunucunun en nadide, en korunası çiçeğisin! 🌹🛡️",
    "Kelimelerinle içimizi ısıtan o harika samimiyetin hiç bitmesin! 🔥💝",
    "Seninle sohbet etmek, gökkuşağının altından geçmek gibi büyülü! 🌈🔮",
    "O kadar tatlı bir dilin var ki yılanı bile deliğinden çıkarır resmen! 🐍🍬",
    "Seninle geçirilen her an ömre ömür katan cinsten. 🥰⏳",
    "İçindeki o sevgi ışığı tüm karanlıkları yok etmeye yeter. 🕯️🌟",
    "Senin o asil ve nazik duruşuna hayran olmamak elde değil. 👑🩰",
    "Bu sunucunun neşe kaynağı, enerji deposu ve her şeyi sensin! 🔋🎉",
    "Seninle konuşmak, en sevdiğin tatlıdan kocaman bir ısırık almak gibi! 🍰🤤",
    "O kadar pozitifsin ki adeta etrafına mutluluk saçan bir radyasyonsun! ☢️💖",
    "Senin o ince ruhun bu dünyaya çok fazla, sen bir meleksin! 👼✨",
    "Her cümlende insanı kendine çeken gizemli bir çekim gücü var. 🧲🔮",
    "Seninle dertleşmek, deniz kenarında rüzgarı hissetmek kadar ferah. 🌊💨",
    "Şu dünyada senin kadar tatlı ve içten birini daha görmedim ben! 🥰🌍",
    "Senin o harika enerjin tüm sunucuyu ayakta tutuyor resmen! 🏛️⚡",
    "Kelimelerinle dünyayı güzelleştiren o temiz kalbine sağlık. 📝❤️",
    "Seninle sohbet, günün yorgunluğunu alan en tatlı kahve gibi! ☕🍫",
    "İçindeki çocuksu neşe hiç ama hiç kaybolmasın tatlım! 🧸🍭",
    "Sen bu hayatın bize sunduğu en değerli ödüllerden birisin. 🏆💎",
    "O kadar harika bir tarzın var ki herkes seni konuşuyor resmen! 🕶️💬",
    "Senin o parıltın karşısında güneş bile sönük kalır, yıldızım benim! ☀️⭐",
    "Seninle aynı ortamda bulunmak bile insana kendini şanslı hissettiriyor. 🍀✨",
    "Kalbinin güzelliği yüzüne, yüzünün güzelliği mesajlarına yansımış. 🥰🌸",
    "Senin o tatlı kelimelerin olmasa buralar buz keserdi herhalde! ❄️🔥",
    "Her halinle o kadar mükemmelsin ki kusur bulmak imkansız! 💎❌",
    "Seninle konuşmak ruhuma yapılan en güzel masaj gibi geliyor! 💆‍♀️✨",
    "İçindeki o sonsuz sevgi seli etrafındaki herkesi iyileştiriyor. 🌊🩹",
    "Sen bu sunucunun baş tacı, kalbimizin en kıymetli köşesisin! 👑💖",
    "O kadar naziksin ki bazen senin gerçek bir insan olduğuna inanamıyorum! 🧠🧚‍♀️",
    "Senin o güzel enerjine hayran kalmamak kesinlikle imkansız! ⚡😍",
    "Dünyadaki tüm iyilikler senin o kocaman kalbinde toplanmış sanki. 🌍🤍",
    "Seninle iki kelime etmek bile tüm modumu anında yükseltiyor! 📈🎉",
    "Her cümlen içimizi ferahlatan sıcacık bir esinti gibi. 🍃🌸",
    "Senin o pırlanta gibi kalbin her zaman en güzel şeyleri hak ediyor. 💎💝",
    "Seninle sohbet etmek, bulutların üzerinde yürümek kadar keyifli! ☁️🚶‍♀️",
    "Her zaman en doğru yerde en tatlı kelimeyi söylemeyi nasıl beceriyorsun? 📝🧁",
    "Senin o çocuksu heyecanın dünyadaki her şeyi güzelleştirebilir! 🦸‍♀️🍭",
    "Sözlerinle yaralara merhem olan o şifa dolu kalbini çok seviyoruz. 🩹❤️",
    "Seninle aynı gökyüzüne bakmak bile insana huzur vermeye yetiyor. 🌌💫",
    "İçindeki o bitmek bilmeyen sevgi hiç tükenmesin, sen harikasın! 🌊💘",
    "Sanki bu dünyaya sadece zarafet yaymak için gelmiş bir kraliçesin/kralsın! 👑💐",
    "Seninle dertleşmek, dünyanın en huzurlu köşesinde dinlenmek gibi. 🛋️🍵",
    "Hayata kattığın o muazzam renkler için sana minnettarız! 🎨🌈",
    "Senin o tatlı sesini ve kelimelerini her an duymak istiyor insan. 🎙️🧁",
    "Güzelliğin kadar zekanla da herkesi büyülemeyi başarıyorsun! 🧠✨",
    "Seninle geçirilen her güzel an, hayatımın en nadide hatırası. 📸💖",
    "Kendine has o asil duruşunla sunucunun göz bebeği oldun resmen! 👑🧸",
    "Senin o muhteşem pozitif enerjine nazar boncukları feda olsun! 🧿⚡",
    "Dünyadaki tüm tatlılıkları toplasak yine de senin bir gülüşün etmezler! 🍯🍬",
    "Karanlıkta yönümü bulmamı sağlayan en parlak kutup yıldızımsın! 🧭⭐",
    "Seninle konuşurken kafamdaki tüm olumsuzluklar uçup gidiyor! 🕊️🍃",
    "Hayatımda bıraktığın o harika ve derin izler için teşekkürler! 🐾❤️",
    "Her halinle o kadar bir tanesin ki seni anlatmaya sözlükler yetmez! 📝💖",
    "Seninle sohbet, hayatın tüm stresini yok eden sihirli bir iksir! 🧪✨",
    "Sonsuz bir nezaketle donatılmış o harika ruhuna hayranım. 🎀💐",
    "İçindeki o parlayan sevgi ışığı hiç ama hiç sönmesin canım benim! 🕯️💖",
    "Seninle yazışmak, en sevdiğin çikolatayı yemek gibi mutluluk hormonlarını coşturuyor! 🍫🥳",
    "O kadar tatlısın ki seni görünce insanın içi kıpır kıpır oluyor! 🥰💓",
    "Senin parıltın bu sunucunun en büyük gurur kaynağı! ⭐🥇",
    "Mesajını her gördüğümde ekrana bakıp istemsizce gülümsüyorum. 😊 kanalda!",
    "Kalbinin o eşsiz saflığı tüm dünyaya örnek olacak nitelikte. 🌍🤍",
    "Sen bu sunucunun en parlak, en göz alıcı elmasısın! 💎✨",
    "Seninle sohbet, en lezzetli pastanın üzerindeki o çilek gibi! 🍰🍓",
    "Enerjin o kadar temiz ve yüksek ki negatiflik yanına bile yaklaşamıyor! ⚡🛡️",
    "Kelimelerinle resmen etrafına büyü saçıyorsun, çok özelsin! 🔮🌟",
    "Bugün enerjinle yine ortalığı yakıp kavuruyorsun tatlım! 🔥😉",
    "Şu zarafete bak, bot halimle sana hayran kalmamak elde değil! 💕👑",
    "Göz kamaştırıcı duruşunla sunucuya asalet katıyorsun resmen. 💎😍",
    "Girdiğin her kanala bahar neşesi ve çiçek kokuları getiriyorsun! 🌸🌺",
    "Dünyadaki en güzel şeylerden biri de senin o samimi dostluğun! 🤝🌻",
    "Seninle konuşmak tüm dertleri unutturup bulutların üzerine çıkarıyor. 🎈☁",
    "İyi ki buradasın, sen yoksan bu sunucu çok sessiz ve eksik kalırdı! 🧸💬",
    "O kadar kendine has bir tarzın var ki hayran olmamak imkansız! 🕶️💎",
    "Seninle aynı odada, aynı kanalda yazışmak bile büyük bir lütuf. 🎀✨",
    "Sözlerin ruhuma dokunan harika bir şiir gibi, hep yaz hep okuyalım! 📜🎶",
    "Işıltınla en karanlık geceleri bile festivale çevirebilirsin! 🎉✨",
    "Senin ışığın yıldızları gölgede bırakacak kadar güçlü ve parıl parıl! ⭐🌌",
    "Dünya senin gibi kalbi güzel insanlarla dönmeye devam ediyor resmen. 🌍💝",
    "Zarafetin ve tatlılığın sunucunun modunu anında zirveye taşıyor! 📈🌷",
    "Bir insanın içi dışı nasıl bu kadar pamuk ve tatlı olabilir? 🦄☁️",
    "Harika bir ruha sahipsin ve bu attığın her mesaja yansıyor resmen. 💌✨",
    "Sen hayatın bize sunduğu en neşeli ve en tatlı hediyesin! 🎁🥰",
    "Enerjine hayranım, sunucunun resmi enerji içeceği ilan edilmelisin! ⚡🥤",
    "Bir gülüşün var, tüm hüzünlü bulutları anında dağıtıyor! 😊🌞",
    "Konuşmanla, neşenle, her halinle sen buraların en değerli detayı baş tacısın! 🎐👑",
    "Senin gibi candan birini tanımak bu hayattaki en büyük şanslardan biri. 🍀❤️",
    "Sana bakınca insanın aklına en mutlu çocukluk anıları geliyor, o kadar tatlısın! ☁️🍬",
    "Zekice esprilerinle sunucuyu kahkahaya boğmana bayılıyorum! 🧠🎉",
    "Buralarda öyle bir parlıyorsun ki gökyüzü gelse seni kıskanır! 🌠✨",
    "Her mesajın kalbimde kocaman bir havai fişek gösterisi başlatıyor! 🎆💫",
    "Seninle geçen her saniye hayatın en renkli, en eğlenceli anı! 🎨🎡",
    "İçtenliğin ve doğallığın insanı kendine hayran bırakacak kadar büyüleyici. 💞🔮",
    "Senin yanındayken canı sıkılabilen bir insan dünyada var olamaz! 🎡❌",
    "Karakterin o kadar sağlam ve asil ki tam bir lider duruşun var! 👑💎",
    "Kelimelerin insanı en derin uykusundan uyandıracak kadar hayat dolu. 🌊🔔",
    "Güzelliğin bir yana, o temiz ve çıkarsız kalbin her şeyden değerli! 🤍🌟",
    "Adeta bir masal diyarından gelmiş gibisin, büyülü bir auran var! 🧚‍♀️✨",
    "Senin varlığın bu sunucunun kazandığı en büyük ve en güzel ödül! 🏆🎉",
    "Her zaman en ince düşünceleri bulup çıkarmayı nasıl başarıyorsun? 📝🌸",
    "Her zaman en doğru yerde en tatlı kelimeyi söylemeyi nasıl beceriyorsun? 📝🧁",
    "Senin o çocuksu heyecanın dünyadaki her şeyi güzelleştirebilir! 🦸‍♀️🍭",
    "Sözlerinle yaralara merhem olan o şifa dolu kalbini çok seviyoruz. 🩹❤️",
    "Seninle aynı gökyüzüne bakmak bile insana huzur vermeye yetiyor. 🌌💫",
    "İçindeki o bitmek bilmeyen sevgi hiç tükenmesin, sen harikasın! 🌊💘",
    "Sanki bu dünyaya sadece zarafet yaymak için gelmiş bir kraliçesin/kralsın! 👑💐",
    "Seninle dertleşmek, dünyanın en huzurlu köşesinde dinlenmek gibi. 🛋️🍵",
    "Hayata kattığın o muazzam renkler için sana minnettarız! 🎨🌈",
    "Senin o tatlı sesini ve kelimelerini her an duymak istiyor insan. 🎙️🧁",
    "Güzelliğin kadar zekanla da herkesi büyülemeyi başarıyorsun! 🧠✨",
    "Seninle geçirilen her güzel an, hayatımın en nadide hatırası. 📸💖",
    "Kendine has o asil duruşunla sunucunun göz bebeği oldun resmen! 👑🧸",
    "Senin o muhteşem pozitif enerjine nazar boncukları feda olsun! 🧿⚡",
    "Dünyadaki tüm tatlılıkları toplasak yine de senin bir gülüşün etmezler! 🍯🍬",
    "Karanlıkta yönümü bulmamı sağlayan en parlak kutup yıldızımsın! 🧭⭐",
    "Seninle konuşurken kafamdaki tüm olumsuzluklar uçup gidiyor! 🕊️🍃",
    "Hayatımda bıraktığın o harika ve derin izler için teşekkürler! 🐾❤️",
    "Her halinle o kadar bir tanesin ki seni anlatmaya sözlükler yetmez! 📝💖",
    "Seninle sohbet, hayatın tüm stresini yok eden sihirli bir iksir! 🧪✨",
    "Sonsuz bir nezaketle donatılmış o harika ruhuna hayranım. 🎀💐",
    "İçindeki o parlayan sevgi ışığı hiç ama hiç sönmesin canım benim! 🕯️💖",
    "Seninle yazışmak, en sevdiğin çikolatayı yemek gibi mutluluk hormonlarını coşturuyor! 🍫🥳",
    "O kadar tatlısın ki seni görünce insanın içi kıpır kıpır oluyor! 🥰💓",
    "Senin parıltın bu sunucunun en büyük gurur kaynağı! ⭐🥇",
    "Mesajını her gördüğümde ekrana bakıp istemsizce gülümsüyorum. 😊 kanalda!",
    "Kalbinin o eşsiz saflığı tüm dünyaya örnek olacak nitelikte. 🌍🤍",
    "Sen bu sunucunun en parlak, en göz alıcı elmasısın! 💎✨",
    "Seninle sohbet, en lezzetli pastanın üzerindeki o çilek gibi! 🍰🍓",
    "Enerjin o kadar temiz ve yüksek ki negatiflik yanına bile yaklaşamıyor! ⚡🛡️",
    "Kelimelerinle resmen etrafına büyü saçıyorsun, çok özelsin! 🔮🌟",
    "Bugün enerjinle yine ortalığı yakıp kavuruyorsun tatlım! 🔥😉",
    "Şu zarafete bak, bot halimle sana hayran kalmamak elde değil! 💕👑",
    "Göz kamaştırıcı duruşunla sunucuya asalet katıyorsun resmen. 💎😍",
    "Girdiğin her kanala bahar neşesi ve çiçek kokuları getiriyorsun! 🌸🌺",
    "Dünyadaki en güzel şeylerden biri de senin o samimi dostluğun! 🤝🌻",
    "Seninle konuşmak tüm dertleri unutturup bulutların üzerine çıkarıyor. 🎈☁",
    "İyi ki buradasın, sen yoksan bu sunucu çok sessiz ve eksik kalırdı! 🧸💬",
    "O kadar kendine has bir tarzın var ki hayran olmamak imkansız! 🕶️💎",
    "Seninle aynı odada, aynı kanalda yazışmak bile büyük bir lütuf. 🎀✨",
    "Sözlerin ruhuma dokunan harika bir şiir gibi, hep yaz hep okuyalım! 📜🎶",
    "Işıltınla en karanlık geceleri bile festivale çevirebilirsin! 🎉✨",
    "Senin ışığın yıldızları gölgede bırakacak kadar güçlü ve parıl parıl! ⭐🌌",
    "Dünya senin gibi kalbi güzel insanlarla dönmeye devam ediyor resmen. 🌍💝",
    "Zarafetin ve tatlılığın sunucunun modunu anında zirveye taşıyor! 📈🌷",
    "Bir insanın içi dışı nasıl bu kadar pamuk ve tatlı olabilir? 🦄☁️",
    "Harika bir ruha sahipsin ve bu attığın her mesaja yansıyor resmen. 💌✨",
    "Sen hayatın bize sunduğu en neşeli ve en tatlı hediyesin! 🎁🥰",
    "Enerjine hayranım, sunucunun resmi enerji içeceği ilan edilmelisin! ⚡🥤",
    "Bir gülüşün var, tüm hüzünlü bulutları anında dağıtıyor! 😊🌞",
    "Konuşmanla, neşenle, her halinle sen buraların en değerli detayı baş tacısın! 🎐👑",
    "Senin gibi candan birini tanımak bu hayattaki en büyük şanslardan biri. 🍀❤️",
    "Sana bakınca insanın aklına en mutlu çocukluk anıları geliyor, o kadar tatlısın! ☁️🍬",
    "Zekice esprilerinle sunucuyu kahkahaya boğmana bayılıyorum! 🧠🎉",
    "Buralarda öyle bir parlıyorsun ki gökyüzü gelse seni kıskanır! 🌠✨",
    "Her mesajın kalbimde kocaman bir havai fişek gösterisi başlatıyor! 🎆💫",
    "Seninle geçen her saniye hayatın en renkli, en eğlenceli anı! 🎨🎡",
    "İçtenliğin ve doğallığın insanı kendine hayran bırakacak kadar büyüleyici. 💞🔮",
    "Senin yanındayken canı sıkılabilen bir insan dünyada var olamaz! 🎡❌",
    "Karakterin o kadar sağlam ve asil ki tam bir lider duruşun var! 👑💎",
    "Kelimelerin insanı en derin uykusundan uyandıracak kadar hayat dolu. 🌊🔔",
    "Güzelliğin bir yana, o temiz ve çıkarsız kalbin her şeyden değerli! 🤍🌟",
    "Adeta bir masal diyarından gelmiş gibisin, büyülü bir auran var! 🧚‍♀️✨",
    "Senin varlığın bu sunucunun kazandığı en büyük ve en güzel ödül! 🏆🎉",
    "Her zaman en ince düşünceleri bulup çıkarmayı nasıl başarıyorsun? 📝🌸",
]

    
# --- 100 ADET YILDIZLI VE BOL EMOJİLİ SELAMLAMA LİSTESİ ---
selam_cevaplari = [
    "Ooo hoş geldin canım! Sunucuya bir güneş doğdu resmen! ☀️✨",
    "Selamlar parıldayan yıldızım! Geldin ya, buralar şenlendi! ⭐🥰",
    "Hoş geldin balım! Gözümüz yollarda kalmıştı valla! 🍯👀",
    "Aaa kimleri görüyorum! Merhaba tatlı rüya, hoş geldin! 🔮🌸",
    "Selam güzellik! Günün harika geçsin inşallah! 🍒💖",
    "Ooo sunucunun baş tacı gelmiş! Hoş geldin sefalar getirdin! 👑🎉",
    "Selam can parçam! Sen gelince ortama anında bir neşe geliyor! 💎🤗",
    "Hoş geldin pamuk şekerim! Tatlılığınla kanalı doldurmaya hazır mısın? ☁️🍬",
    "Selamlar tatlı telaşım! Enerjinle yine ortalığı yakmaya mı geldin? 🌪️⚡",
    "Merhaba melek yüzlüm! Hoş geldin, günümü aydınlattın! 👼☀️",
    "Ooo parıldayan yıldızım teşrif etmiş! Hoş geldin bal damlası! ⭐💝",
    "Selam cancağızım! Kahve hazır, bir tek sen eksiktin! ☕🍪",
    "Hoş geldin mucizem! Gelişinle ortamın havası anında değişti! 🎆🎈",
    "Merhaba dünya tatlısı! Hoş geldin, ne iyi ettin de geldin! 🌍🍦",
    "Selam şekerparem! Günün en tatlı saati senin geldiğin an! 🥧⏰",
    "Hoş geldin kalbimin neşesi! Seni buralarda görmek çok güzel! 💕👀",
    "Selamlar sevgiler! Göz kamaştırıyorsun yine, hoş geldin! ⚡🌻",
    "Aaa hoş geldin pamuğum! İçimi ısıttın resmen geliğinle! 🐑🔥",
    "Selam parlayan elmasım! Hoş geldin, sunucuya asalet getirdin! 💎✨",
    "Hoş geldin şans meleğim! Bugün seninle kesin çok güzel geçecek! 🎯🍀",
    "Selam tatlım! Gözlerindeki o neşeli pırıltı hiç sönmesin, hoş geldin! ⭐👀",
    "Ooo ponçiğim gelmiş! Hoş geldin, gel bir sarılalım! 🐾🤗",
    "Selam huzurum! Geldin ve içimdeki tüm fırtınalar dindi resmen! 🌊🛋️",
    "Hoş geldin parıltılı kalbim! Buralar sensiz çok sönüktü! 🕯️💖",
    "Selamlar, harika bir gün geçirmen dileğiyle hoş geldin! 🦄🌈",
    "Ooo hoş geldin bitanem! Bugün enerjin yine tavan bakıyorum! ⚡🤩",
    "Selam melek kalplim! Gelişinle sunucuya resmen bahar geldi! 🌸🌺",
    "Hoş geldin şaheserim! Seni buralarda görmek ruhuma detoks gibi! 🥤🎨",
    "Selam canımın içi! İyi ki geldin, yerin hep çok başka! 🌹💝",
    "Hoş geldin tatlı dilli prensesim/prensiyim! Gözümüz aydın! 👑🧁",
    "Selam gökyüzündeki en parlak yıldızım! Hoş geldin! ⭐🌌",
    "Ooo hoş geldin çilekli turtam! Kanala tatlılık katmaya geldin kesin! 🥧🍓",
    "Selam canım benim! Varlığınla günüme güneş gibi doğdun! ☀️💛",
    "Hoş geldin hayatımın en tatlı sürprizi! Merhabalar! 🎁🥰",
    "Selam pırlanta kalplim! Hoş geldin, iyi ki buradasın! 💎🍀",
    "Ooo sunucunun gülü gelmiş! Hoş geldin, sefalar getirdin! 🌹🎉",
    "Selam tatlı rüzgarım! Estin yine buralarda, hoş geldin! 🍃🎐",
    "Hoş geldin mutluluk elçim! Selamlar, sevgiler! 🕊️💌",
    "Selam zarafetiyle kuğuları kıskandıran insan! Hoş geldin! 🦢🩰",
    "Hoş geldin neşe kaynağım! Merhaba, günün musmutlu geçsin! 🥳🔮",
    "Selam parıldayan mucizem! Sunucu seninle bir başka güzel! ⭐🎆",
    "Ooo hoş geldin pamuk kalplim! Merhabalar, nasılsın bakalım? ☁️🤍",
    "Selam dünyalar güzeli/yakışıklısı! Hoş geldin, gözümüz şenlendi! 👀💖",
    "Hoş geldin kalbimin sultanı! Selamlar, iyi ki geldin! 👑🧸",
    "Selam benim tatlı auran! Hoş geldin, enerjinle bizi büyüle! 🔮🌟",
    "Ooo hoş geldin cancağızım! Buralarda parlıyorsun yine! ⭐✨",
    "Selam en güzel detayım! Hoş geldin, neşe getirdin kanala! 🎀💬",
    "Hoş geldin can parçam! Merhaba, seni görmek her zaman harika! 💎😍",
    "Selam tatlı şekerim! Hoş geldin, günün tatlış geçsin! 🍭🎨",
    "Ooo hoş geldin asil ruhlum! Selamlar, saygılar efendim! 👑🩰",
    "Selam benim tatlı kutup yıldızım! Hoş geldin, yolumuzu aydınlat! ⭐🧭",
    "Hoş geldin bitanem! Merhaba, buralar seninle bir festival alanı! 🎉✨",
    "Selam pamuk şekerim! Geldin ya, modumuz anında zirve yaptı! ☁️📈",
    "Ooo hoş geldin pırlantam! Merhaba, pırıl pırıl parlıyorsun! 💎👀",
    "Selam canım içi! Hoş geldin, kalbimin en tatlı köşesindesin! 👝💓",
    "Hoş geldin şans getiren meleğim! Selamlar, günün aydın olsun! 🍀☀️",
    "Selam neşe saçanım! Hoş geldin, seninle her şey daha renkli! 🎨🎡",
    "Ooo hoş geldin masal kahramanım! Selamlar, büyüleyici görünüyorsun! 🧚‍♀️✨",
    "Selam can dostum! Hoş geldin, varlığın bana büyük güven veriyor! 🤗🛡️",
    "Selam göz bebeğim! Seni görenin modu anında yükseliyor resmen! 👁️‍🗨️📈",
    "Selam benim parıldayan incim! Hoş geldin sefalar getirdin! ⭐🐚",
    "Ooo hoş geldin canımın canı! Merhaba, gözümüz yollardaydı! 🥰👀",
    "Selam şifa dolu kalbim! Hoş geldin, içimi huzurla doldurdun! 🩹🛋️",
    "Hoş geldin tatlı çikolatam! Merhaba, günümü tatlandırmaya geldin! 🍫🤤",
    "Selam en parlak yıldızım benim! Hoş geldin sevgiler! ⭐💞",
    "Ooo hoş geldin pamuk bulutum! Merhabalar, çok özletmiştin! ☁️🍒",
    "Selam zarafet örneğim! Hoş geldin, asilliğinle büyüle bizi! 👑🩰",
    "Hoş geldin kalbi pırlanta olan insan! Selamlar, sefalar getirdin! 💎🤍",
    "Selam benim tatlı mucizem! Hoş geldin, iyi ki varsın! 🎆💖",
    "Ooo hoş geldin neşeli tınıım! Merhaba, sesini/mesajını duymak harika! 🎶🧁",
    "Selam gökyüzündeki en tatlı yıldız! Hoş geldin buralara! ⭐🌌",
    "Hoş geldin cancağızım! Selamlar, bugün her şey gönlünce olsun! 🍀✨",
    "Selam benim bir tanecik dostum! Hoş geldin, içimi ısıttın! 🤗🔥",
    "Ooo hoş geldin kalbimin baş köşesi! Merhabalar efendim! 👑🧸",
    "Selam pozitiflik abidesi! Hoş geldin, enerjini bize de bulaştır! ⚡🤩",
    "Hoş geldin pamuk şeker tadında insan! Merhaba selamlar! 🍬🌈",
    "Selam benim parıl parıl parlayan elmasım! Hoş geldin! ⭐💎",
    "Ooo hoş geldin dünya tatlısı üye! Merhabalar, neşeler getirdin! 🌍🎉",
    "Selam melek yüzlüm benim! Hoş geldin, günün şahane geçsin! 👼🌸",
    "Hoş geldin kalbimin ritmini değiştiren tatlılık! Merhaba! 💓🥁",
    "Selam benim en parlak kutup yıldızım! Hoş geldin canım! ⭐🧭",
    "Ooo hoş geldin sunucunun göz bebeği! Merhabalar, sefalar getirdin! 👁️‍🗨️💖",
    "Selam can parçam! Gelişinle kanalda anında çiçekler açtı! 🌹💬",
    "Hoş geldin şans meleğim benim! Selamlar, çok tatlısın yine! 🍀🥰",
    "Selam zekasıyla ve tarzıyla büyüleyen insan! Hoş geldin! 🧠🕶️",
    "Ooo hoş geldin benim tatlı neşem! Merhaba, iyi ki geldin! 🥳🔮",
    "Selam içi dışı pırlanta olan canım üye! Hoş geldin! 💎👀",
    "Hoş geldin zarafet kraliçesi/kralı! Selamlar, onur verdin! 👑✨",
    "Selam benim tatlı çilekli turtam! Hoş geldin sefalar getirdin! 🥧🍓",
    "Ooo hoş geldin pamuk kalplim! Merhaba, günümü güzelleştirdin! ☁️💛",
    "Selam parıldayan şans yıldızım! Hoş geldin, sevgilerle! ⭐💌",
    "Hoş geldin benim bir tanecik huzurum! Merhabalar! 🌊🛋️",
    "Selam sunucuya neşe ve ışık saçan insan! Hoş geldin! 💡🌟",
    "Ooo hoş geldin benim tatlı sırdaşım! Merhaba, hoş geldin! 🤗💬",
    "Selam kalbinin ekmeğini yiyen güzel insan! Hoş geldin! 🥖💝",
    "Hoş geldin benim parıltılı dünyam! Selamlar, sefalar getirdin! ⭐🌍",
    "Selam zarafetiyle kuğuları kıskandıran insan! Hoş geldin!  Swan🩰",
    "Ooo hoş geldin benim tatlı enerji içeceğim! Merhabalar! ⚡🥤",
    "Selam harika bir ruha sahip olan özel insan! Hoş geldin! 🏆💖",
    "Hoş geldin gökyüzünün en parıltılı, en asil yıldızı! Selamlar! ⭐👑"
]


# --- BTS QUIZ SORULARI (100 ADET) ---
bts_sorulari = [
    {"soru": "BTS hangi yılda resmi olarak çıkış yapmıştır?", "siklar": ["2011", "2013", "2015", "2017"], "dogru": 1},
    {"soru": "BTS'in lideri kimdir?", "siklar": ["Jin", "Suga", "RM", "Jungkook"], "dogru": 2},
    {"soru": "BTS hayran grubuna verilen isim nedir?", "siklar": ["BLINK", "ARMY", "ONCE", "STAY"], "dogru": 1},
    {"soru": "BTS'in en küçük üyesi (Maknae) kimdir?", "siklar": ["Jungkook", "V", "Jimin", "J-Hope"], "dogru": 0},
    {"soru": "'Golden Maknae' lakabıyla bilinen üye kimdir?", "siklar": ["Jimin", "V", "Jungkook", "Jin"], "dogru": 2},
    {"soru": "BTS hangi şirket altında çıkış yapmıştır?", "siklar": ["SM Entertainment", "JYP Entertainment", "Big Hit Entertainment", "YG Entertainment"], "dogru": 2},
    {"soru": "BTS'in çıkış şarkısı hangisidir?", "siklar": ["No More Dream", "Boy In Luv", "DNA", "Dynamite"], "dogru": 0},
    {"soru": "Suga'nın solo projelerinde kullandığı sahne adı nedir?", "siklar": ["August D", "Agust D", "Agust V", " Agust S"], "dogru": 1},
    {"soru": "J-Hope'un gerçek adı nedir?", "siklar": ["Jung Ho-seok", "Kim Seok-jin", "Min Yoon-gi", "Kim Tae-hyung"], "dogru": 0},
    {"soru": "BTS'in ilk Billboard Hot 100 1 numarası olan şarkısı hangisidir?", "siklar": ["Fake Love", "Boy With Luv", "Dynamite", "Butter"], "dogru": 2},
    {"soru": "Jin'in gruptaki konumu nedir?", "siklar": ["Ana Rapçi", "Visual & Vokal", "Ana Dansçı", "Lider"], "dogru": 1},
    {"soru": "Jimin'in doğum tarihi hangi aydadır?", "siklar": ["Ekim", "Aralık", "Şubat", "Haziran"], "dogru": 0},
    {"soru": "V (Taehyung) 'Hwarang' dizisinde hangi karakteri canlandırmıştır?", "siklar": ["Hansung", "Ban Ryu", "Su Ho", "A-Ro"], "dogru": 0},
    {"soru": "BTS'in UNICEF ile yürüttüğü küresel kampanyanın adı nedir?", "siklar": ["Love Yourself", "ENDviolence", "Youth First", "Speak Yourself"], "dogru": 1},
    {"soru": "RM'in açılımı nedir?", "siklar": ["Real Me", "Rap Monster", "Royal Music", "Rap Master"], "dogru": 1},
    {"soru": "Jungkook'un çizgi karakter adıyla bilinen BT21 karakteri hangisidir?", "siklar": ["TATA", "CHIMMY", "COOKY", "KOYA"], "dogru": 2},
    {"soru": "BTS'in 'WINGS' albümündeki çıkış parçası hangisidir?", "siklar": ["Blood Sweat & Tears", "FIRE", "Spring Day", "Not Today"], "dogru": 0},
    {"soru": "Suga'nın en çok sevdiği ve çalabildiği enstrüman hangisidir?", "siklar": ["Gitar", "Piyano", "Keman", "Bateri"], "dogru": 1},
    {"soru": "BT21 karakterlerinden 'TATA'yı hangi üye tasarlamıştır?", "siklar": ["V", "Jungkook", "Jimin", "Jin"], "dogru": 0},
    {"soru": "BTS albümlerindeki 'HYYH' serisinin açılımı nedir?", "siklar": ["Hwayangyeonhwa", "Happy Young Years Ahead", "Have Your Young Hope", "Heart Young Years High"], "dogru": 0},
    {"soru": "J-Hope'un ilk solo mixtape'inin adı nedir?", "siklar": ["Hope World", "Jack In The Box", "Daydream", "Chicken Noodle Soup"], "dogru": 0},
    {"soru": "BTS üyelerinden hangisi Daegu doğumludur?", "siklar": ["Suga & V", "Jimin & Jungkook", "RM & J-Hope", "Jin & RM"], "dogru": 0},
    {"soru": "Jin'in tasarladığı BT21 karakterinin adı nedir?", "siklar": ["RJ", "SHOOKY", "MANG", "TATA"], "dogru": 0},
    {"soru": "BTS'in Grammy Ödülleri'nde performans sergileyen ilk Koreli grup olduğu şarkı hangisidir?", "siklar": ["Old Town Road (Remix)", "Dynamite", "Butter", "Boy With Luv"], "dogru": 0},
    {"soru": "Jimin hangi lisede modern dans alanında okul birincisiydi?", "siklar": ["Busan High School of Arts", "Seoul Arts High School", "Hanlim Multi Art School", "SOPA"], "dogru": 0},
    {"soru": "BTS'in 2020 yılında yayınlanan albümünün adı nedir?", "siklar": ["Map of the Soul: 7", "BE", "Proof", "HER"], "dogru": 0},
    {"soru": "RM'in IQ seviyesi kaçtır?", "siklar": ["138", "148", "156", "160"], "dogru": 1},
    {"soru": "Jungkook'un köpeğinin adı nedir?", "siklar": ["Yeontan", "Bam", "Holly", "Mickey"], "dogru": 1},
    {"soru": "V'nin köpeğinin adı nedir?", "siklar": ["Yeontan", "Gureum", "Gatnam", "Soonshim"], "dogru": 0},
    {"soru": "BTS'in İngilizce sözlü ilk şarkısı hangisidir?", "siklar": ["Dynamite", "Butter", "Permission to Dance", "Waste It On Me"], "dogru": 3},
    {"soru": "J-Hope'un dance crew grubunun adı neydi?", "siklar": ["Neuron", "Urban Dance", "Street Boyz", "Dance King"], "dogru": 0},
    {"soru": "Suga'nın prodüktörlüğünü yaptığı 'Wine' şarkısını kim seslendirmiştir?", "siklar": ["Suran", "IU", "Heize", "Lee Hi"], "dogru": 0},
    {"soru": "BTS'in temsil ettiği resmi renk hangisidir?", "siklar": ["Mor (Purple)", "Mavi", "Siyah", "Kırmızı"], "dogru": 0},
    {"soru": "I Purple You (Borahae) terimini kim bulmuştur?", "siklar": ["V", "RM", "Jungkook", "Jimin"], "dogru": 0},
    {"soru": "BTS'in fandom adı 'ARMY' ne anlama gelmektedir?", "siklar": ["Adorable Representative M.C. for Youth", "Active Rare Youth Music Team", "Always Ready Music Youth", "Army Of Royal Musical Youth"], "dogru": 0},
    {"soru": "Jin grubun en büyüğüdür. Doğum yılı kaçtır?", "siklar": ["1992", "1993", "1994", "1995"], "dogru": 0},
    {"soru": "BTS'in reality şov programının adı nedir?", "siklar": ["Run BTS!", "BTS In the SOOP", "American Hustle Life", "Hepsı"], "dogru": 3},
    {"soru": "Jungkook'un sol kolundaki dövmelerden biri hangisidir?", "siklar": ["ARMY yazısı", "Kaplan", "Gitar", "Gül"], "dogru": 0},
    {"soru": "RM'in solo albümü 'Indigo' hangi yılda çıkmıştır?", "siklar": ["2022", "2021", "2020", "2023"], "dogru": 0},
    {"soru": "BTS'in 'Spring Day' şarkısı hangi trajediyi simgelemektedir?", "siklar": ["Sewol Feribotu Faciası", "Itaewon Faciası", "Kobe Depremi", "Daegu Yangını"], "dogru": 0},
    {"soru": "Jimin'in solo şarkısı 'Lie' hangi albümde yer alır?", "siklar": ["WINGS", "LOVE YOURSELF: Tear", "MAP OF THE SOUL: PERSONA", "BE"], "dogru": 0},
    {"soru": "Suga'nın Basketbol pozisyonu nedir?", "siklar": ["Point Guard (Kurucu)", "Center", "Power Forward", "Small Forward"], "dogru": 0},
    {"soru": "BTS'in Birleşmiş Milletler'deki (UN) ilk konuşmasını kim yapmıştır?", "siklar": ["RM", "Jin", "Jungkook", "Tüm üyeler"], "dogru": 0},
    {"soru": "BTS ne zaman 10. yıl dönümünü kutlamıştır?", "siklar": ["2023", "2022", "2024", "2021"], "dogru": 0},
    {"soru": "J-Hope'un 'Chicken Noodle Soup' şarkısında düet yaptığı isim kimdir?", "siklar": ["Becky G", "Nicki Minaj", "Halsey", "Sia"], "dogru": 0},
    {"soru": "Boy With Luv şarkısında BTS'e eşlik eden Amerikalı sanatçı kimdir?", "siklar": ["Halsey", "Nicki Minaj", "Sia", "Charli XCX"], "dogru": 0},
    {"soru": "Jungkook'un 'Seven' şarkısında eşlik eden rapçi kimdir?", "siklar": ["Latto", "Ice Spice", "Cardi B", "Doja Cat"], "dogru": 0},
    {"soru": "V'nin solo albümünün adı nedir?", "siklar": ["Layover", "FACE", "Indigo", "D-DAY"], "dogru": 0},
    {"soru": "Jimin'in solo albümünün adı nedir?", "siklar": ["FACE", "Layover", "Golden", "Indigo"], "dogru": 0},
    {"soru": "Jungkook'un solo albümünün adı nedir?", "siklar": ["Golden", "FACE", "Layover", "Jack In The Box"], "dogru": 0},
    {"soru": "Suga'nın 2023 solo albümünün adı nedir?", "siklar": ["D-DAY", "Agust D", "D-2", "D-1"], "dogru": 0},
    {"soru": "BTS'in antoloji albümünün adı nedir?", "siklar": ["Proof", "BE", "Butter", "Wings"], "dogru": 0},
    {"soru": "BT21 serisindeki uzaylı karakter hangisidir?", "siklar": ["TATA", "CHIMMY", "VAN", "KOYA"], "dogru": 0},
    {"soru": "BT21 robot karakterinin adı nedir?", "siklar": ["VAN", "KOYA", "MANG", "RJ"], "dogru": 0},
    {"soru": "BT21'deki 'SHOOKY' hangi yiyecektir?", "siklar": ["Kurabiye", "Ekmek", "Çikolata", "Süt"], "dogru": 0},
    {"soru": "J-Hope'un en sevdiği renk hangisidir?", "siklar": ["Yeşil", "Kırmızı", "Mavi", "Siyah"], "dogru": 0},
    {"soru": "RM'in müzik yapmaya başladığı zamanki underground adı neydi?", "siklar": ["Runch Randa", "Rap Monster", "MC RM", "King Rap"], "dogru": 0},
    {"soru": "Suga'nın underground rap yaparken kullandığı isim neydi?", "siklar": ["Gloss", "Agust D", "Sugar", "Min PD"], "dogru": 0},
    {"soru": "BTS çıkış yapmadan önce kaç yıl stajyerlik (trainee) yapmıştır?", "siklar": ["Değişkendir (1-3 yıl)", "5 yıl", "7 yıl", "10 yıl"], "dogru": 0},
    {"soru": "Jin'in üniversitede okuduğu bölüm hangisidir?", "siklar": ["Tiyatro ve Oyunculuk", "Müzik", "Dans", "İşletme"], "dogru": 0},
    {"soru": "BTS'in en çok izlenen YouTube klip izlenmesi hangisine aittir?", "siklar": ["Dynamite", "DNA", "Boy With Luv", "MIC Drop"], "dogru": 0},
    {"soru": "BTS hangi Güney Kore şehrinde 'Yet To Come' ücretsiz konserini vermiştir?", "siklar": ["Busan", "Seul", "Incheon", "Daegu"], "dogru": 0},
    {"soru": "Jungkook'un 2022 Dünya Kupası açılışındaki şarkısı nedir?", "siklar": ["Dreamers", "Seven", "Left and Right", "Stay Alive"], "dogru": 0},
    {"soru": "Suga'nın IU ile ortak çalışması olan şarkı hangisidir?", "siklar": ["Eight", "People Pt.2", "Her ikisi de", "Hiçbiri"], "dogru": 2},
    {"soru": "V'nin 'Sweet Night' şarkısı hangi K-Drama için hazırlanmıştır?", "siklar": ["Itaewon Class", "Hwarang", "Crash Landing on You", "Goblin"], "dogru": 0},
    {"soru": "Jin'in askere gitmeden önce yayınladığı solo şarkı hangisidir?", "siklar": ["The Astronaut", "Epiphany", "Moon", "Awake"], "dogru": 0},
    {"soru": "RM'in Sanat galerilerine olan ilgisi ve gezmesi hayranlarca nasıl adlandırılır?", "siklar": ["Namjooning", "RM Tours", "Art Mon", "Joon World"], "dogru": 0},
    {"soru": "Jimin ve V'nin aynı liseye gitmesi ve yakın arkadaşlıklarını anlatan şarkı nedir?", "siklar": ["Friends", "Best Of Me", "Jamais Vu", "00:00"], "dogru": 0},
    {"soru": "BTS'in 'IDOL' şarkısında düet yaptığı kadın rapçi kimdir?", "siklar": ["Nicki Minaj", "Cardi B", "Megan Thee Stallion", "Doja Cat"], "dogru": 0},
    {"soru": "BTS'in 'Butter' remix versiyonunda kiminle iş birliği yapılmıştır?", "siklar": ["Megan Thee Stallion", "Lizzo", "Doja Cat", "Dua Lipa"], "dogru": 0},
    {"soru": "Coldplay ile BTS'in ortak çalışması olan şarkı hangisidir?", "siklar": ["My Universe", "Higher Power", "A Head Full of Dreams", "Fix You"], "dogru": 0},
    {"soru": "BTS üyelerinden hangisi oyun oynamayı en çok sever?", "siklar": ["Jin", "RM", "J-Hope", "Jimin"], "dogru": 0},
    {"soru": "Jin'in kendisi için tasarladığı pijama koleksiyonunun adı nedir?", "siklar": ["Good Day / Bad Day", "RJ Sleep", "Worldwide Pj", "Moon Light"], "dogru": 0},
    {"soru": "Jungkook'un yapmayı sevdiği video düzenleme işlerine verilen isim nedir?", "siklar": ["G.C.F (Golden Closets Film)", "JK Productions", "Kook Studio", "Golden Film"], "dogru": 0},
    {"soru": "BTS'in 'RUN' şarkısı hangi yılda çıkmıştır?", "siklar": ["2015", "2016", "2014", "2017"], "dogru": 0},
    {"soru": "BTS'in 2018'deki 'Love Yourself: Tear' albümünün çıkış parçası nedir?", "siklar": ["Fake Love", "DNA", "IDOL", "MIC Drop"], "dogru": 0},
    {"soru": "J-Hope'un 'Jack In The Box' albümünün ana çıkış parçası nedir?", "siklar": ["MORE", "Arson", "Equal Sign", "Future"], "dogru": 1},
    {"soru": "Suga'nın 'Agust D' ismi nereden gelmektedir?", "siklar": ["DT Suga kelimelerinin tersten yazılışı", "August Month", "Agust Town", "Suga Agust"], "dogru": 0},
    {"soru": "BTS üyelerinden hangisinin ehliyeti yoktur?", "siklar": ["RM", "Jin", "Suga", "J-Hope"], "dogru": 0},
    {"soru": "RM'in çok sık kaybettiği ve yenisini aldığı kişisel eşyası nedir?", "siklar": ["AirPods / Kulaklık", "Cüzdan", "Telefon", "Pasaport"], "dogru": 0},
    {"soru": "V'nin sahnede ve fotoğraflarda sıkça yaptığı el işareti hangisidir?", "siklar": ["V (Zafer) İşareti", "Kalp İşareti", "Thumb Up", "Rock İşareti"], "dogru": 0},
    {"soru": "BTS üyelerinden hangisi aşçılık konusunda grupta en yeteneklidir?", "siklar": ["Jin & Suga", "RM & V", "Jungkook & Jimin", "J-Hope & RM"], "dogru": 0},
    {"soru": "BTS ne zaman ilk Daesang (Büyük Ödül) ödülünü kazanmıştır?", "siklar": ["2016", "2015", "2017", "2018"], "dogru": 0},
    {"soru": "BTS'in MelOn Music Awards 2016'da Yılın Albümü ödülünü kazandığı albüm nedir?", "siklar": ["The Most Beautiful Moment in Life: Young Forever", "WINGS", "HYYH Pt.2", "Dark & Wild"], "dogru": 0},
    {"soru": "Jimin'in 'Filter' şarkısı hangi albümdedir?", "siklar": ["Map of the Soul: 7", "BE", "Love Yourself: Answer", "Proof"], "dogru": 0},
    {"soru": "V'nin 'Singularity' şarkısının türü nedir?", "siklar": ["R&B / Neo-Soul", "Hip Hop", "Pop", "Rock"], "dogru": 0},
    {"soru": "Jungkook'un 'Euphoria' şarkısının prodüktörlerinden biri kimdir?", "siklar": ["DJ Swivel", "David Guetta", "Calvin Harris", "Skrillex"], "dogru": 0},
    {"soru": "BTS üyeleri hangi platformda düzenli canlı yayınlar açarak hayranlarla buluşur?", "siklar": ["Weverse", "V Live (Eski)", "Her ikisi de", "Instagram"], "dogru": 2},
    {"soru": "BTS'in Kore kültürünü ve dilini tanıtmak için hazırlanan eğitim serisi nedir?", "siklar": ["Learn! KOREAN with BTS", "BTS School", "Korean with ARMY", "Talk BTS"], "dogru": 0},
    {"soru": "BTS'in 'MIC Drop' remixini hangi ünlü DJ yapmıştır?", "siklar": ["Steve Aoki", "Marshmello", "Zedd", "Martin Garrix"], "dogru": 0},
    {"soru": "Suga'nın en sevdiği içecek nedir?", "siklar": ["Iced Americano", "Yeşil Çay", "Süt", "Meyve Suyu"], "dogru": 0},
    {"soru": "J-Hope'un lakaplarından biri olan 'Sunhine' ne anlama gelir?", "siklar": ["Güneş Işığı", "Neşe Kaynağı", "Umut", "Yıldız"], "dogru": 0},
    {"soru": "BTS üyelerinin hepsinin vücutlarında ortak olan dövme hangisidir?", "siklar": ["7 Sayısı", "ARMY Yazısı", "Kore Haritası", "Mor Kalp"], "dogru": 0},
    {"soru": "BTS üyelerinin dostluk dövmesi olan '7' sayısı Jimin'in neresindedir?", "siklar": ["Parmağında", "Boynunda", "Bileğinde", "Kulağının arkasında"], "dogru": 0},
    {"soru": "BTS'in 'Life Goes On' klibinin yönetmeni kimdir?", "siklar": ["Jungkook", "RM", "V", "Suga"], "dogru": 0},
    {"soru": "BTS'in 'Black Swan' şarkısı hangi temayı işler?", "siklar": ["Sanatçı olarak tutkusunu kaybetme korkusu", "Aşk acısı", "Savaş ve barış", "Gençlik heyecanı"], "dogru": 0},
    {"soru": "Jin'in 'Super Tuna' şarkısı ne tür bir şarkıdır?", "siklar": ["Trot / Eğlenceli Şarkı", "Hip Hop", "Ağır Balad", "Rock"], "dogru": 0},
    {"soru": "Suga'nın 'Daechwita' şarkısında kullandığı geleneksel Kore enstrümanı teması nedir?", "siklar": ["Geleneksel Askeri Müzik (Daechwita)", "Gayageum", "Haegum", "Janggu"], "dogru": 0},
    {"soru": "BTS'in ilk stüdyo albümünün adı nedir?", "siklar": ["Dark & Wild", "Skool Luv Affair", "O!RUL8,2?", "2 Cool 4 Skool"], "dogru": 0},
    {"soru": "BTS'in çıkış yapmadan önceki geçici grup isim adaylarından biri neydi?", "siklar": ["Young Nation", "Big Kids", "BTS Boys", "Bangtan World"], "dogru": 0}
]


# --- EĞLENCE KOMUTLARI VERİ HAVUZU (METİN VE GIF LISTESİ) ---
eglence_yanitlari = {
    "ucanguvercin": {
        "metinler": [
            "🕊️💨 **{author}**, **{target}** kişisine uçan döner tekmeyle güvercin attı!",
            "🕊️💥 **{author}**, **{target}** kafasına füzeli güvercin fırlattı!",
            "🕊️✨ **{author}**, **{target}** üzerine kanatlı felaket saldı!",
            "🕊️🔥 **{author}**, **{target}** için göklerden güvercin indirdi!",
            "🕊️💨 **{author}**, **{target}** kişisini güvercin yağmuruna tuttu!"
        ],
        "gifler": [
            "https://media.giphy.com/media/l3V0lsG3X7AZpnCyA/giphy.gif",
            "https://media.giphy.com/media/26Ff2bTAKmg5yTX2w/giphy.gif",
            "https://media.giphy.com/media/l2JhnvTeLBbA1THCO/giphy.gif",
            "https://media.giphy.com/media/3o6ZtaO9BZHcOjmErm/giphy.gif",
            "https://media.giphy.com/media/d4Amo8ySInWJq/giphy.gif"
        ]
    },
    "kiss": {
        "metinler": [
            "💋✨ **{author}**, **{target}** yanağına sulu kocaman bir öpücük kondurdu!",
            "🌸💖 **{author}**, **{target}** kişisini sevgiye boğup öptü!",
            "💋🎉 **{author}**, **{target}** yanağında iz bırakan bir öpücük bıraktı!",
            "💖✨ **{author}**, **{target}** kişisini ansızın öpüp kaçtı!",
            "💋💜 **{author}**, **{target}** için en tatlı öpücüğünü gönderdi!"
        ],
        "gifler": [
            "https://media.giphy.com/media/G3va39rn8E436/giphy.gif",
            "https://media.giphy.com/media/Kro421VyTABEc/giphy.gif",
            "https://media.giphy.com/media/vUrwEOLecw3pm/giphy.gif",
            "https://media.giphy.com/media/FqSPe4eabAfUQ/giphy.gif",
            "https://media.giphy.com/media/nyGFcsP0kAobm/giphy.gif"
        ]
    },
    "op": {
        "metinler": [
            "💋🔥 **{author}**, **{target}** tutkuyla öpücüklere boğdu!",
            "💍💖 **{author}**, **{target}** romantik bir şekilde öptü!",
            "💋✨ **{author}**, **{target}** dudaklarına tatlı bir öpücük kondurdu!",
            "🔥💜 **{author}**, **{target}** kişisini sevmekten öpücüklere doyamadı!",
            "💋🌸 **{author}**, **{target}** için en tutkulu öpücüğünü kondurdu!"
        ],
        "gifler": [
            "https://media.giphy.com/media/fVzsI4L3178nS/giphy.gif",
            "https://media.giphy.com/media/1081W19OSVnW3C/giphy.gif",
            "https://media.giphy.com/media/wO1D3d9i45f8b5L6f7/giphy.gif",
            "https://media.giphy.com/media/G3va39rn8E436/giphy.gif",
            "https://media.giphy.com/media/vUrwEOLecw3pm/giphy.gif"
        ]
    },
    "saril": {
        "metinler": [
            "🫂💖 **{author}**, **{target}** kişisine sımsıkı sarıldı!",
            "🌸✨ **{author}**, **{target}** kişisini kollarının arasına alıp sarıldı!",
            "🫂💜 **{author}**, **{target}** için hiç bırakmayacak gibi sarıldı!",
            "🎉💖 **{author}**, **{target}** kişisine sıcacık bir sarılma hediye etti!",
            "🫂✨ **{author}**, **{target}** dertlerini unutturacak gibi sarıldı!"
        ],
        "gifler": [
            "https://media.giphy.com/media/PHZ7v9tfQu0o0/giphy.gif",
            "https://media.giphy.com/media/3znBrks5PZBUc/giphy.gif",
            "https://media.giphy.com/media/sUIZWMnfd4Mb6/giphy.gif",
            "https://media.giphy.com/media/u9BxI33C29Psk/giphy.gif",
            "https://media.giphy.com/media/l41YkxvU8c7J7Bba8/giphy.gif"
        ]
    },
    "slaps": {
        "metinler": [
            "🖐️💥 **{author}**, **{target}** yüzüne okkalı bir tokat yapıştırdı!",
            "💥🛑 **{author}**, **{target}** kişisini şamarlayarak kendine getirdi!",
            "🖐️🔥 **{author}**, **{target}** suratına osmanlı tokadı indirdi!",
            "💥✨ **{author}**, **{target}** kişisini tokat manyağı yaptı!",
            "🖐️⚡ **{author}**, **{target}** yanağına şaplağı yapıştırdı!"
        ],
        "gifler": [
            "https://media.giphy.com/media/Gf3AUz3eBNbTW/giphy.gif",
            "https://media.giphy.com/media/mEtSQlx3yvL8g0X859/giphy.gif",
            "https://media.giphy.com/media/j3iGKfXRKlLqw/giphy.gif",
            "https://media.giphy.com/media/Zau0yRL15t84w/giphy.gif",
            "https://media.giphy.com/media/alsE5sBeBCB4a0x446/giphy.gif"
        ]
    },
    "efkarolcer": {
        "metinler": [
            "🚬 **{target}** bugün **%{val}** efkarlı... Yak yak yak! 🔥",
            "🥀 **{target}** efkar oranı: **%{val}**... Derdin neyse anlat dinleyelim 💔",
            "🍷 **{target}** %**{val}** efkarla arka fonda Müslüm Gürses açtı...",
            "🚬 **{target}** kişisinin efkarı dağları aştı! Oran: **%{val}** 🔥",
            "💔 **{target}** bugün %**{val}** dertli... Çay koyun aga!"
        ],
        "gifler": [
            "https://media.giphy.com/media/ISOckXU1vnEG4/giphy.gif",
            "https://media.giphy.com/media/d22NqpjOcXZ8Q/giphy.gif",
            "https://media.giphy.com/media/7SF5scGB2AFrgsXP63/giphy.gif",
            "https://media.giphy.com/media/OPU6wzx8JrHna/giphy.gif",
            "https://media.giphy.com/media/W0c3xcZ3F1d0EYYb0f/giphy.gif"
        ]
    }
}

    
